services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports:
      - 3306:3306

  adminer:
    image: adminer
    depends_on:
      - mysql
    ports:
      - 8080:8080

  rust:
    build: .
    environment:
      DATABASE_URL: mysql://root:password@db/db
      API_ADDR: 0.0.0.0:3000
      SQLX_OFFLINE: true
    depends_on:
      - mysql
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    command: cargo run --release
