name: Cargo Setups

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  DATABASE_URL: postgres://user:password@localhost/db
  API_ADDR: 1.2.3.4:5678
  SQLX_OFFLINE: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run build
      run: cargo build --verbose

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test --verbose

  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run formatter
      run: |
        cargo fmt
        git diff --numstat

        if [ $(git diff --numstat | wc -l) -gt 0 ]; then exit 1; fi

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run linter
      run: |
        cargo clippy -- \
          -W clippy::pedantic \
          -W clippy::nursery \
          -W clippy::unwrap_used \
          -W clippy::expect_used

        LINTER_OUTPUT=$(
          cargo clippy -- \
            -W clippy::pedantic \
            -W clippy::nursery \
            -W clippy::unwrap_used \
            -W clippy::expect_used  2>&1
        )

        if [ $(echo "$LINTER_OUTPUT" | wc -l) -gt 10 ]; then exit 1; fi
